In [56]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
import xgboost as xgb
import lightgbm as lgb
from catboost import CatBoostRegressor


from sklearn.model_selection import cross_val_score

In [2]:
x = pd.read_csv(r"../data/selected/selcetd_train_x.csv")
y=pd.read_csv(r"../data/selected/train_y.csv")

x = x.drop(columns="Unnamed: 0")
y =y.drop(columns="Unnamed: 0")

In [3]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [4]:
x_train
y_train =y_train.squeeze()
y_test=y_test.squeeze()

In [5]:
x = x_train.copy()
y=y_train.copy()
xt=x_test.copy()
yt=y_test.copy()

In [6]:
x=x.drop(columns=['RemodelAge',"HouseAge","GarageType_Detchd","Foundation_PConc","MasVnrType_None"])

xt=xt.drop(columns=['RemodelAge',"HouseAge","GarageType_Detchd","Foundation_PConc","MasVnrType_None"])

In [7]:
#linear tree regression

LRM = LinearRegression()

LRM.fit(x_train,y_train)

predicted = LRM.predict(x_test)

In [8]:
comparison_df = pd.concat(
    [
        y_test.reset_index(drop=True),
        pd.DataFrame(predicted, columns=["Predicted"])
    ],
    axis=1
)

#rsquraed
r2 = r2_score(y_test,comparison_df["Predicted"])
mae = mean_absolute_error(y_test,comparison_df["Predicted"])
mse= mean_squared_error(y_test,comparison_df["Predicted"])
rmse = np.sqrt(mse)
n=x_test.shape[0]
k=x_test.shape[1]
adjusted_r2 = 1 - ((1 - r2) * (n - 1) / (n - k - 1))
print(f"""r2 : {r2}
        mae : {mae}
        mse : {mse}
        rmse : {rmse}
        adjusted_re :{adjusted_r2}
""")

c_score = cross_val_score(
    LRM,
    x_train,
    y_train,
    cv=5,
    scoring="r2"
)

c_score.mean()

r2 : 0.8537733687915492
        mae : 20859.714235233423
        mse : 1020383142.9188632
        rmse : 31943.43661722801
        adjusted_re :0.8382252206630557

np.float64(0.7750841215374218)

In [9]:
#decision tree

DTR = DecisionTreeRegressor(random_state=42)

DTR.fit(x_train,y_train)

y_predict = DTR.predict(x_test)

In [10]:
comparison_df_dtr= pd.concat([
        y_test.reset_index(drop=True),
        pd.DataFrame(y_predict, columns=["Predicted"])],axis=1)

r2 = r2_score(y_test,comparison_df_dtr["Predicted"])
mae = mean_absolute_error(y_test,comparison_df_dtr["Predicted"])
mse= mean_squared_error(y_test,comparison_df_dtr["Predicted"])
n=x_test.shape[0]
k=x_test.shape[1]
adjusted_r2 = 1 - ((1 - r2) * (n - 1) / (n - k - 1))
rmse = np.sqrt(mse)
print(f"""r2 : {r2}
        mae : {mae}
        mse : {mse}
        rmse : {rmse}
        adjusted_re :{adjusted_r2}
""")

c_score = cross_val_score(
    DTR,
    x_train,
    y_train,
    cv=5,
    scoring="r2"
)

c_score.mean()

r2 : 0.811791625191952
        mae : 25017.931506849316
        mse : 1313335686.0045662
        rmse : 36239.97359276861
        adjusted_re :0.7917795954655267

np.float64(0.6459044225274161)

In [11]:
#random forest

RDG = RandomForestRegressor(random_state=42)

RDG.fit(x_train,y_train)

RDG_Predict = RDG.predict(x_test)

In [12]:
comparison_df_RDG = pd.concat([
        y_test.reset_index(drop=True),
        pd.DataFrame(RDG_Predict, columns=["Predicted"])],axis=1)

comparison_df_RDG

r2 = r2_score(y_test,comparison_df_RDG["Predicted"])
mae = mean_absolute_error(y_test,comparison_df_RDG["Predicted"])
mse= mean_squared_error(y_test,comparison_df_RDG["Predicted"])
rmse = np.sqrt(mse)
n=x_test.shape[0]
k=x_test.shape[1]
adjusted_r2 = 1 - ((1 - r2) * (n - 1) / (n - k - 1))
print(f"""r2 : {r2}
    mae : {mae}
    mse : {mse}
    rmse : {rmse}
    adjusted_r2 : {adjusted_r2}
        
""")

cv = cross_val_score(
    RDG,
    x_train,
    y_train,
    cv=5,
    scoring="r2"
)
print("avg r2 : ",cv.mean())

r2 : 0.9001814179683261
    mae : 16993.145410958907
    mse : 696543424.5010324
    rmse : 26392.10913324345
    adjusted_r2 : 0.889567796587743


avg r2 :  0.8120856303643796

In [13]:
#gradient boost regressor

GRB = GradientBoostingRegressor(random_state=42,learning_rate=0.1,max_depth=3,n_estimators=100,subsample=1.0,)

GRB.fit(x, y_train)

y_pred = GRB.predict(xt)

In [14]:
comparison_df_GRB = pd.concat([
        y_test.reset_index(drop=True),
        pd.DataFrame(y_pred, columns=["Predicted"])],axis=1)

comparison_df_GRB

     SalePrice      Predicted
0       154500  141931.530042
1       325000  348758.814257
2       115000  127104.088535
3       159000  146498.007851
4       315500  319942.822244
..         ...            ...
433     139000  129744.942613
434     126175  124252.100887
435     205950  194403.805522
436     110000  135188.849633
437     485000  507461.857091

[438 rows x 2 columns]

In [15]:
r2 = r2_score(y_test,comparison_df_GRB["Predicted"])
mae = mean_absolute_error(y_test,comparison_df_GRB["Predicted"])
mse= mean_squared_error(y_test,comparison_df_GRB["Predicted"])
rmse = np.sqrt(mse)
n=xt.shape[0]
k=xt.shape[1]
adjusted_r2 = 1 - ((1 - r2) * (n - 1) / (n - k - 1))
print(f"""r2 : {r2}
    mae : {mae}
    mse : {mse}
    rmse : {rmse}
    adjusted_r2 : {adjusted_r2}
        
""")

cv = cross_val_score(
    GRB,
    x_train,
    y_train,
    cv=5,
    scoring="r2"
)
print("avg r2 : ",cv.mean())

r2 : 0.9080235776445127
    mae : 16983.670026456777
    mse : 641820098.9923444
    rmse : 25334.168606692907
    adjusted_r2 : 0.8995157585766301


avg r2 :  0.8034950504115311

In [16]:
#xgb regressor
xgb_op  = xgb.XGBRegressor(random_state=42,max_depth=7,n_estimators=300,subsample =0.8)
xgb_op.fit(x_train, y_train)
y_pred = xgb_op.predict(x_test)

In [17]:
comparison_df_xgb = pd.concat([
        y_test.reset_index(drop=True),
        pd.DataFrame(y_pred, columns=["Predicted"])],axis=1)

comparison_df_GRB

r2 = r2_score(y_test,comparison_df_GRB["Predicted"])
mae = mean_absolute_error(y_test,comparison_df_GRB["Predicted"])
mse= mean_squared_error(y_test,comparison_df_GRB["Predicted"])
rmse = np.sqrt(mse)
n=x_test.shape[0]
k=x_test.shape[1]
adjusted_r2 = 1 - ((1 - r2) * (n - 1) / (n - k - 1))
print(f"""r2 : {r2}
    mae : {mae}
    mse : {mse}
    rmse : {rmse}
    adjusted_r2 : {adjusted_r2}
        
""")

cv = cross_val_score(
    GRB,
    x_train,
    y_train,
    cv=5,
    scoring="r2"
)
print("avg r2 : ",cv.mean())

r2 : 0.9080235776445127
    mae : 16983.670026456777
    mse : 641820098.9923444
    rmse : 25334.168606692907
    adjusted_r2 : 0.8982438061535495


avg r2 :  0.8034950504115311

In [18]:
#lgbm regressor

In [19]:
LGB = lgb.LGBMRegressor(random_state=42,learning_rate=0.05,max_depth=None,n_estimators=100,num_leaves=50)

LGB.fit(x, y_train)

y_pred = LGB.predict(xt)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000630 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2622
[LightGBM] [Info] Number of data points in the train set: 1022, number of used features: 37
[LightGBM] [Info] Start training from score 181312.692759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [20]:
comparison_df_lgbr = pd.concat([
        y_test.reset_index(drop=True),
        pd.DataFrame(y_pred, columns=["Predicted"])],axis=1)

r2 = r2_score(y_test,comparison_df_lgbr["Predicted"])
mae = mean_absolute_error(y_test,comparison_df_lgbr["Predicted"])
mse= mean_squared_error(y_test,comparison_df_lgbr["Predicted"])
rmse = np.sqrt(mse)
n=x.shape[0]
k=xt.shape[1]
adjusted_r2 = 1 - ((1 - r2) * (n - 1) / (n - k - 1))
print(f"""r2 : {r2}
        mae : {mae}
        mse : {mse}
        rmse : {rmse}
        adjusted_r2 : {adjusted_r2}
""")

cv = cross_val_score(
    LGB,
    x_train,
    y_train,
    cv=5,
    scoring="r2"
)
cv.mean()

r2 : 0.8809118730523475
        mae : 17305.112760962646
        mse : 831008115.6553615
        rmse : 28827.211374938117
        adjusted_r2 : 0.876433965839885

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000532 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2646
[LightGBM] [Info] Number of data points in the train set: 817, number of used features: 42
[LightGBM] [Info] Start training from score 179744.681763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000551 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2651
[LightGBM] [Info] Number of data points in the train set: 817, number of used features: 42
[LightGBM] [Info] Start training from score 181110.870257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000415 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2671
[LightGBM] [Info] Number of data points in the train set: 818, number of used features: 42
[LightGBM] [Info] Start training from score 182547.721271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

np.float64(0.8375612430233362)

In [21]:
#catboost regressor
CBR = CatBoostRegressor(random_state=42)

CBR.fit(x_train,y_train)

cbr_predict = CBR.predict(x_test)

Learning rate set to 0.041084
0:	learn: 75597.8604469	total: 53.6ms	remaining: 53.6s
1:	learn: 73709.3172597	total: 58.6ms	remaining: 29.3s
2:	learn: 71930.0775930	total: 61.6ms	remaining: 20.5s
3:	learn: 70149.5127890	total: 67.2ms	remaining: 16.7s
4:	learn: 68464.4320860	total: 70.5ms	remaining: 14s
5:	learn: 66890.3597452	total: 74.4ms	remaining: 12.3s
6:	learn: 65433.4329022	total: 77.2ms	remaining: 10.9s
7:	learn: 63833.3493247	total: 81.2ms	remaining: 10.1s
8:	learn: 62311.7990001	total: 83.9ms	remaining: 9.24s
9:	learn: 61044.5991176	total: 85.8ms	remaining: 8.49s
10:	learn: 59702.7459005	total: 88.4ms	remaining: 7.95s
11:	learn: 58452.4458067	total: 90.2ms	remaining: 7.43s
12:	learn: 57177.3070281	total: 91.9ms	remaining: 6.98s
13:	learn: 56004.6654464	total: 93.6ms	remaining: 6.59s
14:	learn: 54837.0885878	total: 95.2ms	remaining: 6.25s
15:	learn: 53769.3928072	total: 97.1ms	remaining: 5.97s
16:	learn: 52727.5291729	total: 98.7ms	remaining: 5.71s
17:	learn: 51651.7243967	total: 101ms	remaining: 5.51s
18:	learn: 50529.0906069	total: 103ms	remaining: 5.3s
19:	learn: 49555.2674694	total: 104ms	remaining: 5.09s
20:	learn: 48653.4205391	total: 105ms	remaining: 4.91s
21:	learn: 47812.1314597	total: 107ms	remaining: 4.74s
22:	learn: 47024.9619469	total: 108ms	remaining: 4.58s
23:	learn: 46215.3970908	total: 109ms	remaining: 4.44s
24:	learn: 45405.2876559	total: 110ms	remaining: 4.3s
25:	learn: 44631.4165102	total: 112ms	remaining: 4.19s
26:	learn: 43902.0462754	total: 113ms	remaining: 4.08s
27:	learn: 43193.8394960	total: 115ms	remaining: 3.98s
28:	learn: 42510.3704883	total: 116ms	remaining: 3.88s
29:	learn: 41896.2802117	total: 117ms	remaining: 3.8s
30:	learn: 41223.9874426	total: 119ms	remaining: 3.72s
31:	learn: 40579.6320949	total: 120ms	remaining: 3.64s
32:	learn: 39966.1654796	total: 122ms	remaining: 3.57s
33:	learn: 39341.9252609	total: 123ms	remaining: 3.49s
34:	learn: 38720.3973436	total: 124ms	remaining: 3.43s
35:	learn: 38152.2725867	total: 126ms	remaining: 3.37s
36:	learn: 37695.2802950	total: 128ms	remaining: 3.32s
37:	learn: 37213.2521726	total: 129ms	remaining: 3.27s
38:	learn: 36611.9612692	total: 131ms	remaining: 3.22s
39:	learn: 36204.4108552	total: 132ms	remaining: 3.18s
40:	learn: 35715.0963713	total: 134ms	remaining: 3.13s
41:	learn: 35284.1769910	total: 135ms	remaining: 3.08s
42:	learn: 34812.6197145	total: 137ms	remaining: 3.04s
43:	learn: 34382.7152836	total: 138ms	remaining: 2.99s
44:	learn: 33947.6906334	total: 139ms	remaining: 2.95s
45:	learn: 33559.0140734	total: 141ms	remaining: 2.92s
46:	learn: 33195.5541087	total: 142ms	remaining: 2.88s
47:	learn: 32734.7425841	total: 144ms	remaining: 2.86s
48:	learn: 32350.3974020	total: 146ms	remaining: 2.83s
49:	learn: 31972.8634057	total: 147ms	remaining: 2.8s
50:	learn: 31616.5208372	total: 148ms	remaining: 2.76s
51:	learn: 31289.9699070	total: 150ms	remaining: 2.73s
52:	learn: 30937.8157725	total: 151ms	remaining: 2.7s
53:	learn: 30606.3064847	total: 153ms	remaining: 2.67s
54:	learn: 30269.3876034	total: 154ms	remaining: 2.65s
55:	learn: 29967.8390341	total: 156ms	remaining: 2.62s
56:	learn: 29654.9932067	total: 157ms	remaining: 2.6s
57:	learn: 29424.7910673	total: 159ms	remaining: 2.58s
58:	learn: 29140.6194908	total: 160ms	remaining: 2.56s
59:	learn: 28928.5608472	total: 162ms	remaining: 2.53s
60:	learn: 28683.7739838	total: 163ms	remaining: 2.51s
61:	learn: 28482.5761934	total: 164ms	remaining: 2.48s
62:	learn: 28275.0288715	total: 166ms	remaining: 2.46s
63:	learn: 28056.5163825	total: 167ms	remaining: 2.44s
64:	learn: 27885.7200337	total: 168ms	remaining: 2.42s
65:	learn: 27695.0844132	total: 170ms	remaining: 2.41s
66:	learn: 27470.0894669	total: 172ms	remaining: 2.39s
67:	learn: 27272.2491193	total: 174ms	remaining: 2.38s
68:	learn: 27123.0321433	total: 175ms	remaining: 2.36s
69:	learn: 26941.7183120	total: 176ms	remaining: 2.34s
70:	learn: 26778.4385536	total: 178ms	remaining: 2.32s
71:	learn: 26634.3870537	total: 179ms	remaining: 2.31s
72:	learn: 26472.7065554	total: 182ms	remaining: 2.32s
73:	learn: 26300.0474622	total: 185ms	remaining: 2.31s
74:	learn: 26115.7070527	total: 186ms	remaining: 2.3s
75:	learn: 25972.3937865	total: 188ms	remaining: 2.28s
76:	learn: 25816.0579918	total: 190ms	remaining: 2.27s
77:	learn: 25673.6069451	total: 191ms	remaining: 2.26s
78:	learn: 25554.2020636	total: 193ms	remaining: 2.25s
79:	learn: 25424.7956107	total: 194ms	remaining: 2.23s
80:	learn: 25266.3606716	total: 195ms	remaining: 2.22s
81:	learn: 25128.6912482	total: 197ms	remaining: 2.2s
82:	learn: 24952.8635898	total: 199ms	remaining: 2.19s
83:	learn: 24797.7829101	total: 200ms	remaining: 2.18s
84:	learn: 24668.9303939	total: 202ms	remaining: 2.17s
85:	learn: 24556.9478055	total: 203ms	remaining: 2.16s
86:	learn: 24420.9318547	total: 205ms	remaining: 2.15s
87:	learn: 24287.4383581	total: 206ms	remaining: 2.14s
88:	learn: 24179.2720812	total: 207ms	remaining: 2.12s
89:	learn: 24011.8604175	total: 209ms	remaining: 2.11s
90:	learn: 23934.6497245	total: 210ms	remaining: 2.1s
91:	learn: 23819.4939247	total: 212ms	remaining: 2.09s
92:	learn: 23739.2364326	total: 213ms	remaining: 2.08s
93:	learn: 23673.8023411	total: 215ms	remaining: 2.07s
94:	learn: 23542.2686975	total: 216ms	remaining: 2.06s
95:	learn: 23443.1412167	total: 218ms	remaining: 2.05s
96:	learn: 23338.2794350	total: 219ms	remaining: 2.04s
97:	learn: 23261.1330602	total: 221ms	remaining: 2.03s
98:	learn: 23164.8170677	total: 222ms	remaining: 2.02s
99:	learn: 23083.0012841	total: 223ms	remaining: 2.01s
100:	learn: 22999.8117811	total: 225ms	remaining: 2s
101:	learn: 22917.6361679	total: 226ms	remaining: 1.99s
102:	learn: 22826.5788304	total: 228ms	remaining: 1.98s
103:	learn: 22748.1738363	total: 231ms	remaining: 1.99s
104:	learn: 22650.8065617	total: 233ms	remaining: 1.99s
105:	learn: 22562.7907911	total: 234ms	remaining: 1.98s
106:	learn: 22492.0061132	total: 236ms	remaining: 1.97s
107:	learn: 22405.0011911	total: 237ms	remaining: 1.96s
108:	learn: 22317.5170129	total: 239ms	remaining: 1.95s
109:	learn: 22261.0377636	total: 241ms	remaining: 1.95s
110:	learn: 22245.2642948	total: 243ms	remaining: 1.94s
111:	learn: 22156.9746343	total: 244ms	remaining: 1.94s
112:	learn: 22075.4600243	total: 246ms	remaining: 1.93s
113:	learn: 21997.3063765	total: 248ms	remaining: 1.93s
114:	learn: 21914.7789740	total: 249ms	remaining: 1.92s
115:	learn: 21818.5505037	total: 251ms	remaining: 1.91s
116:	learn: 21749.6991095	total: 253ms	remaining: 1.91s
117:	learn: 21649.3721977	total: 255ms	remaining: 1.91s
118:	learn: 21580.0789443	total: 256ms	remaining: 1.9s
119:	learn: 21479.7995151	total: 258ms	remaining: 1.89s
120:	learn: 21420.5301969	total: 259ms	remaining: 1.89s
121:	learn: 21352.3088616	total: 262ms	remaining: 1.89s
122:	learn: 21272.3133551	total: 264ms	remaining: 1.88s
123:	learn: 21180.2618519	total: 266ms	remaining: 1.88s
124:	learn: 21108.4548355	total: 268ms	remaining: 1.88s
125:	learn: 21037.1584721	total: 270ms	remaining: 1.87s
126:	learn: 20970.5230896	total: 272ms	remaining: 1.87s
127:	learn: 20890.7238217	total: 274ms	remaining: 1.86s
128:	learn: 20831.2605191	total: 275ms	remaining: 1.86s
129:	learn: 20771.3286587	total: 277ms	remaining: 1.85s
130:	learn: 20727.8554749	total: 278ms	remaining: 1.84s
131:	learn: 20670.0356562	total: 280ms	remaining: 1.84s
132:	learn: 20612.7639198	total: 283ms	remaining: 1.84s
133:	learn: 20575.5550378	total: 284ms	remaining: 1.84s
134:	learn: 20523.3821619	total: 286ms	remaining: 1.83s
135:	learn: 20447.4497403	total: 287ms	remaining: 1.83s
136:	learn: 20400.7108799	total: 289ms	remaining: 1.82s
137:	learn: 20347.2255989	total: 291ms	remaining: 1.81s
138:	learn: 20290.1946581	total: 292ms	remaining: 1.81s
139:	learn: 20235.5856127	total: 293ms	remaining: 1.8s
140:	learn: 20180.9071312	total: 295ms	remaining: 1.79s
141:	learn: 20125.6019044	total: 296ms	remaining: 1.79s
142:	learn: 20078.7112079	total: 298ms	remaining: 1.78s
143:	learn: 20027.9516968	total: 299ms	remaining: 1.78s
144:	learn: 19978.3482416	total: 301ms	remaining: 1.77s
145:	learn: 19921.7146926	total: 303ms	remaining: 1.77s
146:	learn: 19865.4895791	total: 304ms	remaining: 1.77s
147:	learn: 19818.0532818	total: 306ms	remaining: 1.76s
148:	learn: 19754.1790502	total: 307ms	remaining: 1.75s
149:	learn: 19690.5991588	total: 309ms	remaining: 1.75s
150:	learn: 19649.4993909	total: 310ms	remaining: 1.74s
151:	learn: 19611.5709813	total: 312ms	remaining: 1.74s
152:	learn: 19569.6519614	total: 313ms	remaining: 1.73s
153:	learn: 19527.7256793	total: 315ms	remaining: 1.73s
154:	learn: 19465.6008093	total: 316ms	remaining: 1.72s
155:	learn: 19403.4772986	total: 318ms	remaining: 1.72s
156:	learn: 19370.4606862	total: 319ms	remaining: 1.71s
157:	learn: 19308.2599809	total: 320ms	remaining: 1.71s
158:	learn: 19253.6719571	total: 322ms	remaining: 1.7s
159:	learn: 19194.7443043	total: 323ms	remaining: 1.7s
160:	learn: 19170.2990380	total: 325ms	remaining: 1.69s
161:	learn: 19116.9109998	total: 326ms	remaining: 1.69s
162:	learn: 19096.1861566	total: 328ms	remaining: 1.68s
163:	learn: 19063.4558520	total: 329ms	remaining: 1.68s
164:	learn: 19005.4470542	total: 331ms	remaining: 1.67s
165:	learn: 18961.2086060	total: 332ms	remaining: 1.67s
166:	learn: 18910.2674448	total: 334ms	remaining: 1.67s
167:	learn: 18853.7765251	total: 335ms	remaining: 1.66s
168:	learn: 18812.3485377	total: 337ms	remaining: 1.66s
169:	learn: 18747.4686538	total: 338ms	remaining: 1.65s
170:	learn: 18690.7492480	total: 339ms	remaining: 1.64s
171:	learn: 18643.9526932	total: 340ms	remaining: 1.64s
172:	learn: 18606.4604812	total: 342ms	remaining: 1.63s
173:	learn: 18551.8268115	total: 344ms	remaining: 1.63s
174:	learn: 18528.6876579	total: 345ms	remaining: 1.63s
175:	learn: 18492.3477102	total: 347ms	remaining: 1.63s
176:	learn: 18463.9760179	total: 349ms	remaining: 1.62s
177:	learn: 18422.6540861	total: 350ms	remaining: 1.62s
178:	learn: 18384.4008347	total: 351ms	remaining: 1.61s
179:	learn: 18339.0703402	total: 353ms	remaining: 1.61s
180:	learn: 18300.2293919	total: 358ms	remaining: 1.62s
181:	learn: 18258.0252401	total: 360ms	remaining: 1.62s
182:	learn: 18233.7175869	total: 361ms	remaining: 1.61s
183:	learn: 18198.0433110	total: 363ms	remaining: 1.61s
184:	learn: 18161.8254780	total: 364ms	remaining: 1.6s
185:	learn: 18122.0162742	total: 365ms	remaining: 1.6s
186:	learn: 18083.0361901	total: 367ms	remaining: 1.59s
187:	learn: 18053.3853988	total: 368ms	remaining: 1.59s
188:	learn: 18015.5515437	total: 371ms	remaining: 1.59s
189:	learn: 17986.0047351	total: 372ms	remaining: 1.59s
190:	learn: 17942.7929925	total: 374ms	remaining: 1.58s
191:	learn: 17897.8063356	total: 376ms	remaining: 1.58s
192:	learn: 17856.0750324	total: 377ms	remaining: 1.58s
193:	learn: 17809.0915273	total: 379ms	remaining: 1.57s
194:	learn: 17762.0068617	total: 380ms	remaining: 1.57s
195:	learn: 17729.7604869	total: 381ms	remaining: 1.56s
196:	learn: 17692.4772417	total: 383ms	remaining: 1.56s
197:	learn: 17657.6316124	total: 384ms	remaining: 1.55s
198:	learn: 17615.4898494	total: 385ms	remaining: 1.55s
199:	learn: 17580.7979480	total: 387ms	remaining: 1.55s
200:	learn: 17547.9696175	total: 388ms	remaining: 1.54s
201:	learn: 17511.4456586	total: 390ms	remaining: 1.54s
202:	learn: 17481.5278323	total: 392ms	remaining: 1.54s
203:	learn: 17432.5718624	total: 394ms	remaining: 1.53s
204:	learn: 17386.1986153	total: 395ms	remaining: 1.53s
205:	learn: 17353.5494039	total: 396ms	remaining: 1.53s
206:	learn: 17329.3538388	total: 398ms	remaining: 1.52s
207:	learn: 17288.1727514	total: 399ms	remaining: 1.52s
208:	learn: 17237.5167263	total: 400ms	remaining: 1.51s
209:	learn: 17198.1739398	total: 402ms	remaining: 1.51s
210:	learn: 17152.5568536	total: 404ms	remaining: 1.51s
211:	learn: 17125.2380176	total: 405ms	remaining: 1.5s
212:	learn: 17100.3692167	total: 407ms	remaining: 1.5s
213:	learn: 17068.5764474	total: 408ms	remaining: 1.5s
214:	learn: 17033.1772208	total: 410ms	remaining: 1.5s
215:	learn: 16987.0063218	total: 412ms	remaining: 1.49s
216:	learn: 16944.6810835	total: 413ms	remaining: 1.49s
217:	learn: 16893.7898270	total: 414ms	remaining: 1.49s
218:	learn: 16864.8662364	total: 416ms	remaining: 1.48s
219:	learn: 16845.4703063	total: 418ms	remaining: 1.48s
220:	learn: 16807.1053378	total: 420ms	remaining: 1.48s
221:	learn: 16753.8207204	total: 421ms	remaining: 1.48s
222:	learn: 16712.5474928	total: 423ms	remaining: 1.47s
223:	learn: 16691.0342078	total: 424ms	remaining: 1.47s
224:	learn: 16648.0008471	total: 426ms	remaining: 1.47s
225:	learn: 16625.5344036	total: 427ms	remaining: 1.46s
226:	learn: 16587.7879705	total: 428ms	remaining: 1.46s
227:	learn: 16547.2448869	total: 430ms	remaining: 1.46s
228:	learn: 16508.5904233	total: 431ms	remaining: 1.45s
229:	learn: 16470.1302778	total: 433ms	remaining: 1.45s
230:	learn: 16442.9460172	total: 435ms	remaining: 1.45s
231:	learn: 16399.6981594	total: 436ms	remaining: 1.44s
232:	learn: 16367.8626151	total: 438ms	remaining: 1.44s
233:	learn: 16329.5504106	total: 439ms	remaining: 1.44s
234:	learn: 16300.2241376	total: 440ms	remaining: 1.43s
235:	learn: 16280.2152272	total: 442ms	remaining: 1.43s
236:	learn: 16258.6375180	total: 444ms	remaining: 1.43s
237:	learn: 16230.8385596	total: 445ms	remaining: 1.43s
238:	learn: 16189.9120645	total: 447ms	remaining: 1.42s
239:	learn: 16145.9460829	total: 448ms	remaining: 1.42s
240:	learn: 16112.0734508	total: 450ms	remaining: 1.42s
241:	learn: 16084.9762966	total: 451ms	remaining: 1.41s
242:	learn: 16057.4278222	total: 453ms	remaining: 1.41s
243:	learn: 16018.8710669	total: 454ms	remaining: 1.41s
244:	learn: 16000.4983417	total: 456ms	remaining: 1.4s
245:	learn: 15963.0354548	total: 457ms	remaining: 1.4s
246:	learn: 15917.2684343	total: 459ms	remaining: 1.4s
247:	learn: 15886.4008251	total: 460ms	remaining: 1.4s
248:	learn: 15846.3123536	total: 462ms	remaining: 1.39s
249:	learn: 15814.4890766	total: 463ms	remaining: 1.39s
250:	learn: 15782.1985847	total: 465ms	remaining: 1.39s
251:	learn: 15757.5022192	total: 467ms	remaining: 1.38s
252:	learn: 15722.6479233	total: 468ms	remaining: 1.38s
253:	learn: 15693.7453183	total: 470ms	remaining: 1.38s
254:	learn: 15663.9726028	total: 471ms	remaining: 1.38s
255:	learn: 15638.9206470	total: 473ms	remaining: 1.37s
256:	learn: 15598.6418392	total: 474ms	remaining: 1.37s
257:	learn: 15564.7633643	total: 475ms	remaining: 1.37s
258:	learn: 15515.7117992	total: 477ms	remaining: 1.36s
259:	learn: 15485.5105129	total: 478ms	remaining: 1.36s
260:	learn: 15449.5901092	total: 480ms	remaining: 1.36s
261:	learn: 15418.0849084	total: 481ms	remaining: 1.35s
262:	learn: 15387.6966974	total: 483ms	remaining: 1.35s
263:	learn: 15343.3904851	total: 485ms	remaining: 1.35s
264:	learn: 15319.5516324	total: 486ms	remaining: 1.35s
265:	learn: 15300.3140350	total: 488ms	remaining: 1.35s
266:	learn: 15263.0446747	total: 489ms	remaining: 1.34s
267:	learn: 15231.1968585	total: 491ms	remaining: 1.34s
268:	learn: 15215.8915110	total: 493ms	remaining: 1.34s
269:	learn: 15181.5235952	total: 494ms	remaining: 1.34s
270:	learn: 15151.8248554	total: 496ms	remaining: 1.33s
271:	learn: 15128.1014467	total: 497ms	remaining: 1.33s
272:	learn: 15088.8445043	total: 499ms	remaining: 1.33s
273:	learn: 15080.5804740	total: 500ms	remaining: 1.32s
274:	learn: 15046.3519300	total: 501ms	remaining: 1.32s
275:	learn: 15032.1031092	total: 503ms	remaining: 1.32s
276:	learn: 14997.2752025	total: 504ms	remaining: 1.31s
277:	learn: 14960.5420079	total: 506ms	remaining: 1.31s
278:	learn: 14934.3619032	total: 508ms	remaining: 1.31s
279:	learn: 14899.1975142	total: 510ms	remaining: 1.31s
280:	learn: 14861.1321658	total: 511ms	remaining: 1.31s
281:	learn: 14829.1254459	total: 513ms	remaining: 1.3s
282:	learn: 14793.0908061	total: 514ms	remaining: 1.3s
283:	learn: 14761.5485152	total: 516ms	remaining: 1.3s
284:	learn: 14756.6434892	total: 517ms	remaining: 1.3s
285:	learn: 14719.9145351	total: 518ms	remaining: 1.29s
286:	learn: 14684.6269910	total: 519ms	remaining: 1.29s
287:	learn: 14649.3939051	total: 521ms	remaining: 1.29s
288:	learn: 14616.5561912	total: 523ms	remaining: 1.29s
289:	learn: 14591.9419221	total: 525ms	remaining: 1.29s
290:	learn: 14566.6773384	total: 527ms	remaining: 1.28s
291:	learn: 14552.5571136	total: 529ms	remaining: 1.28s
292:	learn: 14519.1108946	total: 530ms	remaining: 1.28s
293:	learn: 14514.2236173	total: 532ms	remaining: 1.28s
294:	learn: 14509.4642044	total: 533ms	remaining: 1.27s
295:	learn: 14494.0464104	total: 535ms	remaining: 1.27s
296:	learn: 14468.1833729	total: 536ms	remaining: 1.27s
297:	learn: 14436.6190354	total: 538ms	remaining: 1.27s
298:	learn: 14412.8738899	total: 539ms	remaining: 1.26s
299:	learn: 14384.9561560	total: 541ms	remaining: 1.26s
300:	learn: 14366.5850706	total: 543ms	remaining: 1.26s
301:	learn: 14344.9614697	total: 545ms	remaining: 1.26s
302:	learn: 14320.9380092	total: 546ms	remaining: 1.25s
303:	learn: 14293.0877920	total: 547ms	remaining: 1.25s
304:	learn: 14265.4382442	total: 548ms	remaining: 1.25s
305:	learn: 14222.5305562	total: 549ms	remaining: 1.25s
306:	learn: 14205.1264108	total: 551ms	remaining: 1.24s
307:	learn: 14177.4423311	total: 552ms	remaining: 1.24s
308:	learn: 14151.6964576	total: 554ms	remaining: 1.24s
309:	learn: 14147.0749170	total: 556ms	remaining: 1.24s
310:	learn: 14123.2091813	total: 557ms	remaining: 1.23s
311:	learn: 14098.4885573	total: 559ms	remaining: 1.23s
312:	learn: 14064.7291824	total: 560ms	remaining: 1.23s
313:	learn: 14060.6210181	total: 561ms	remaining: 1.23s
314:	learn: 14030.4763513	total: 563ms	remaining: 1.22s
315:	learn: 14004.0250064	total: 564ms	remaining: 1.22s
316:	learn: 13979.0154775	total: 565ms	remaining: 1.22s
317:	learn: 13960.6998285	total: 567ms	remaining: 1.22s
318:	learn: 13936.5923316	total: 569ms	remaining: 1.21s
319:	learn: 13903.1257883	total: 570ms	remaining: 1.21s
320:	learn: 13873.7019392	total: 572ms	remaining: 1.21s
321:	learn: 13857.2892680	total: 574ms	remaining: 1.21s
322:	learn: 13832.8137658	total: 576ms	remaining: 1.21s
323:	learn: 13811.7297901	total: 578ms	remaining: 1.21s
324:	learn: 13795.5537621	total: 580ms	remaining: 1.2s
325:	learn: 13752.2339046	total: 582ms	remaining: 1.2s
326:	learn: 13722.3596053	total: 585ms	remaining: 1.2s
327:	learn: 13700.9387894	total: 587ms	remaining: 1.2s
328:	learn: 13683.1319804	total: 589ms	remaining: 1.2s
329:	learn: 13635.2175681	total: 593ms	remaining: 1.2s
330:	learn: 13613.4585150	total: 596ms	remaining: 1.2s
331:	learn: 13593.7030289	total: 598ms	remaining: 1.2s
332:	learn: 13575.8222120	total: 601ms	remaining: 1.2s
333:	learn: 13571.7360164	total: 603ms	remaining: 1.2s
334:	learn: 13546.3149969	total: 605ms	remaining: 1.2s
335:	learn: 13537.0919524	total: 608ms	remaining: 1.2s
336:	learn: 13525.4777732	total: 610ms	remaining: 1.2s
337:	learn: 13509.6340197	total: 613ms	remaining: 1.2s
338:	learn: 13504.0196663	total: 615ms	remaining: 1.2s
339:	learn: 13477.7108220	total: 617ms	remaining: 1.2s
340:	learn: 13462.2791855	total: 620ms	remaining: 1.2s
341:	learn: 13441.3943315	total: 622ms	remaining: 1.2s
342:	learn: 13422.3679805	total: 624ms	remaining: 1.2s
343:	learn: 13393.9317040	total: 626ms	remaining: 1.19s
344:	learn: 13370.3603299	total: 629ms	remaining: 1.19s
345:	learn: 13347.1739500	total: 632ms	remaining: 1.19s
346:	learn: 13342.1009614	total: 634ms	remaining: 1.19s
347:	learn: 13320.3489489	total: 635ms	remaining: 1.19s
348:	learn: 13291.4106763	total: 637ms	remaining: 1.19s
349:	learn: 13261.7857601	total: 639ms	remaining: 1.19s
350:	learn: 13253.1613013	total: 641ms	remaining: 1.19s
351:	learn: 13227.8138751	total: 643ms	remaining: 1.18s
352:	learn: 13201.4531618	total: 645ms	remaining: 1.18s
353:	learn: 13177.7060400	total: 647ms	remaining: 1.18s
354:	learn: 13143.2871874	total: 649ms	remaining: 1.18s
355:	learn: 13128.8356784	total: 651ms	remaining: 1.18s
356:	learn: 13102.5412246	total: 653ms	remaining: 1.18s
357:	learn: 13097.4886193	total: 655ms	remaining: 1.17s
358:	learn: 13075.4277992	total: 657ms	remaining: 1.17s

In [22]:
comparison_df_cbr = pd.concat([
        y_test.reset_index(drop=True),
        pd.DataFrame(cbr_predict, columns=["Predicted"])],axis=1)

r2 = r2_score(y_test,comparison_df_cbr["Predicted"])
mae = mean_absolute_error(y_test,comparison_df_cbr["Predicted"])
mse= mean_squared_error(y_test,comparison_df_cbr["Predicted"])
rmse = np.sqrt(mse)
n=x.shape[0]
k=xt.shape[1]
adjusted_r2 = 1 - ((1 - r2) * (n - 1) / (n - k - 1))
print(f"""r2 : {r2}
        mae : {mae}
        mse : {mse}
        rmse : {rmse}
        adjusted_r2 :{adjusted_r2}
""")

cv = cross_val_score(
    LGB,
    x_train,
    y_train,
    cv=5,
    scoring="r2"
)
cv.mean()

r2 : 0.9130134976837346
        mae : 16350.610993694267
        mse : 606999969.0990636
        rmse : 24637.36936239467
        adjusted_r2 :0.9097426637551759

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000600 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2646
[LightGBM] [Info] Number of data points in the train set: 817, number of used features: 42
[LightGBM] [Info] Start training from score 179744.681763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000510 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2651
[LightGBM] [Info] Number of data points in the train set: 817, number of used features: 42
[LightGBM] [Info] Start training from score 181110.870257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000408 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2671
[LightGBM] [Info] Number of data points in the train set: 818, number of used features: 42
[LightGBM] [Info] Start training from score 182547.721271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

np.float64(0.8375612430233362)

In [40]:
comparison_df_cbr

     SalePrice      Predicted
0       154500  145279.133267
1       325000  349666.838134
2       115000  107675.841786
3       159000  143302.153388
4       315500  344330.258648
..         ...            ...
433     139000  134958.467936
434     126175  122390.574865
435     205950  202275.435504
436     110000  140110.307740
437     485000  494115.654009

[438 rows x 2 columns]

In [23]:
# from above all 7 model catboost regressor perform well where it have high r2 score and less mse rmse val compared to others

In [24]:
importance = CBR.get_feature_importance()

importance

array([ 1.61251616,  4.90874839, 16.20725981,  3.45919278,  2.2814886 ,
        0.80113972,  1.11453887,  2.45955569,  1.89443902,  1.80050047,
        2.3870046 ,  0.32337856,  4.9907964 ,  1.48186894,  7.40361006,
        0.7537065 ,  1.34186799,  1.34171906,  1.80042915,  2.53979205,
        2.04677726,  2.25937848,  2.70137395,  1.75577143,  2.47847519,
        0.17883692,  0.02125676,  0.09922963,  0.40962371,  0.212165  ,
        0.1740544 ,  0.05442003,  0.04665361,  0.96706173,  0.18152852,
        0.34828249,  0.53679508,  2.79827847,  1.87067373, 11.3709383 ,
        4.01333064,  4.57154185])

In [49]:
import_feature = pd.DataFrame({
    "col nmae" : x_train.columns, 
    "val" :importance
})
import_feature = import_feature.sort_values(by="val",ascending=False)

import_feature=import_feature.reset_index(drop=True)


import_feature = import_feature.iloc[0:15,0:]

import_feature

filtered_df_train = x_train[["OverallQual","TotalSf","GrLivArea","1stFlrSF","LotArea","TotalLivArea","TotalBathrooms","YearBuilt","HouseAge","GarageArea","FireplaceQu","OpenPorchSF","BsmtQual","TotalBsmtSF","YearRemodAdd"]]
filtered_df_test =x_test[["OverallQual","TotalSf","GrLivArea","1stFlrSF","LotArea","TotalLivArea","TotalBathrooms","YearBuilt","HouseAge","GarageArea","FireplaceQu","OpenPorchSF","BsmtQual","TotalBsmtSF","YearRemodAdd"]]

In [46]:
import_feature

          col nmae        val
0      OverallQual  16.207260
1          TotalSf  11.370938
2        GrLivArea   7.403610
3         1stFlrSF   4.990796
4          LotArea   4.908748
5     TotalLivArea   4.571542
6   TotalBathrooms   4.013331
7        YearBuilt   3.459193
8         HouseAge   2.798278
9       GarageArea   2.701374
10     FireplaceQu   2.539792
11     OpenPorchSF   2.478475
12        BsmtQual   2.459556
13     TotalBsmtSF   2.387005
14    YearRemodAdd   2.281489

In [50]:
filtered_df_train

,OverallQual,TotalSf,GrLivArea,1stFlrSF,LotArea,TotalLivArea,TotalBathrooms,YearBuilt,HouseAge,GarageArea,FireplaceQu,OpenPorchSF,BsmtQual,TotalBsmtSF,YearRemodAdd
135,7,1311.428333,7.428333,7.428333,9.249657,1311.428333,2.0,1970,38,530,4.0,0,2.0,1304,1970
1452,5,553.978214,6.978214,6.978214,8.209580,553.978214,2.0,2005,1,525,0.0,28,3.0,547,2005
762,7,1545.639876,7.344719,6.639876,9.064274,763.344719,2.5,2009,1,614,0.0,45,3.0,756,2009
932,9,1912.552762,7.552762,7.552762,9.364862,1912.552762,2.0,2006,1,788,4.0,191,4.0,1905,2006
435,7,1639.719013,7.415777,6.719013,9.275004,806.415777,3.5,1996,13,550,3.0,61,3.0,799,1996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,6,1321.181592,7.181592,7.181592,9.139703,1321.181592,2.0,2006,1,440,4.0,22,3.0,1314,2006
1130,4,1782.192182,7.591862,7.192182,8.962520,1129.591862,3.0,1928,81,576,3.0,44,2.0,1122,1950
1294,5,870.762730,6.762730,6.762730,9.008591,870.762730,2.0,1955,51,572,0.0,0,2.0,864,1990
860,7,1432.816736,7.263330,6.816736,8.941545,919.263330,1.5,1918,89,216,4.0,240,2.0,912,1998
1126,7,1380.349874,7.349874,7.349874,8.212026,1380.349874,2.0,2007,2,660,3.0,20,3.0,1373,2007

In [51]:
CBR = CatBoostRegressor(random_state=42)

CBR.fit(filtered_df_train,y_train)

predicted=CBR.predict(filtered_df_test)

Learning rate set to 0.041084
0:	learn: 75514.1004700	total: 3.73ms	remaining: 3.73s
1:	learn: 73534.1281764	total: 6.04ms	remaining: 3.01s
2:	learn: 71615.0684628	total: 8.3ms	remaining: 2.76s
3:	learn: 69735.0534390	total: 10.6ms	remaining: 2.64s
4:	learn: 67955.9851199	total: 13.2ms	remaining: 2.62s
5:	learn: 66316.2272124	total: 15.3ms	remaining: 2.53s
6:	learn: 64653.7925010	total: 17.4ms	remaining: 2.46s
7:	learn: 63117.0636420	total: 19.6ms	remaining: 2.43s
8:	learn: 61657.6385438	total: 21.8ms	remaining: 2.4s
9:	learn: 60211.8183133	total: 24ms	remaining: 2.37s
10:	learn: 58796.4222455	total: 26.2ms	remaining: 2.35s
11:	learn: 57433.8682398	total: 28.3ms	remaining: 2.33s
12:	learn: 56232.8725742	total: 30.1ms	remaining: 2.28s
13:	learn: 55111.6732723	total: 31.8ms	remaining: 2.24s
14:	learn: 53960.1402315	total: 33.4ms	remaining: 2.19s
15:	learn: 52835.0764863	total: 35.1ms	remaining: 2.16s
16:	learn: 51727.7746510	total: 36.8ms	remaining: 2.13s
17:	learn: 50670.6251857	total: 38.5ms	remaining: 2.1s
18:	learn: 49672.3911941	total: 40.2ms	remaining: 2.07s
19:	learn: 48730.1907702	total: 43.4ms	remaining: 2.13s
20:	learn: 47791.4304996	total: 45.7ms	remaining: 2.13s
21:	learn: 46869.6600576	total: 47.8ms	remaining: 2.12s
22:	learn: 45991.4838326	total: 49.9ms	remaining: 2.12s
23:	learn: 45151.2738880	total: 51.9ms	remaining: 2.11s
24:	learn: 44400.9707821	total: 54ms	remaining: 2.11s
25:	learn: 43601.5928813	total: 56ms	remaining: 2.1s
26:	learn: 42888.7976844	total: 58.1ms	remaining: 2.09s
27:	learn: 42172.8803087	total: 60.1ms	remaining: 2.08s
28:	learn: 41492.3824765	total: 62.7ms	remaining: 2.1s
29:	learn: 40891.3754494	total: 64.8ms	remaining: 2.09s
30:	learn: 40290.6748798	total: 67.4ms	remaining: 2.11s
31:	learn: 39677.7705365	total: 69.4ms	remaining: 2.1s
32:	learn: 39086.5306029	total: 71.5ms	remaining: 2.1s
33:	learn: 38519.1441250	total: 73.9ms	remaining: 2.1s
34:	learn: 37941.8549556	total: 75.9ms	remaining: 2.09s
35:	learn: 37411.9662264	total: 77.9ms	remaining: 2.08s
36:	learn: 36885.0914056	total: 79.6ms	remaining: 2.07s
37:	learn: 36350.0280662	total: 81.2ms	remaining: 2.06s
38:	learn: 35894.7749106	total: 82.7ms	remaining: 2.04s
39:	learn: 35426.1306239	total: 84.5ms	remaining: 2.03s
40:	learn: 34951.0289017	total: 86ms	remaining: 2.01s
41:	learn: 34510.5003801	total: 87.5ms	remaining: 2s
42:	learn: 34097.7083416	total: 88.9ms	remaining: 1.98s
43:	learn: 33722.3068279	total: 90.1ms	remaining: 1.96s
44:	learn: 33353.1349639	total: 91.4ms	remaining: 1.94s
45:	learn: 32952.0805513	total: 92.6ms	remaining: 1.92s
46:	learn: 32650.4648312	total: 93.9ms	remaining: 1.9s
47:	learn: 32335.2879785	total: 95.1ms	remaining: 1.89s
48:	learn: 32004.7805329	total: 96.4ms	remaining: 1.87s
49:	learn: 31667.6715772	total: 97.6ms	remaining: 1.85s
50:	learn: 31368.5175724	total: 98.7ms	remaining: 1.84s
51:	learn: 31043.4957093	total: 99.9ms	remaining: 1.82s
52:	learn: 30768.5258910	total: 101ms	remaining: 1.8s
53:	learn: 30455.3860057	total: 102ms	remaining: 1.79s
54:	learn: 30170.4726106	total: 103ms	remaining: 1.77s
55:	learn: 29888.7225041	total: 104ms	remaining: 1.75s
56:	learn: 29634.0421609	total: 105ms	remaining: 1.74s
57:	learn: 29368.0369991	total: 106ms	remaining: 1.72s
58:	learn: 29112.8408108	total: 108ms	remaining: 1.71s
59:	learn: 28869.2738461	total: 109ms	remaining: 1.7s
60:	learn: 28619.6878774	total: 109ms	remaining: 1.69s
61:	learn: 28402.3417631	total: 110ms	remaining: 1.67s
62:	learn: 28198.7148346	total: 111ms	remaining: 1.65s
63:	learn: 27996.8575645	total: 112ms	remaining: 1.64s
64:	learn: 27820.8715469	total: 113ms	remaining: 1.62s
65:	learn: 27620.0857247	total: 114ms	remaining: 1.61s
66:	learn: 27402.7185341	total: 115ms	remaining: 1.6s
67:	learn: 27197.7018257	total: 116ms	remaining: 1.59s
68:	learn: 27029.3736100	total: 117ms	remaining: 1.58s
69:	learn: 26869.6983450	total: 118ms	remaining: 1.57s
70:	learn: 26676.7364991	total: 119ms	remaining: 1.56s
71:	learn: 26469.3143081	total: 120ms	remaining: 1.55s
72:	learn: 26316.7221273	total: 121ms	remaining: 1.54s
73:	learn: 26106.8890946	total: 122ms	remaining: 1.53s
74:	learn: 25982.1895190	total: 123ms	remaining: 1.52s
75:	learn: 25817.5798115	total: 124ms	remaining: 1.51s
76:	learn: 25665.3802878	total: 126ms	remaining: 1.51s
77:	learn: 25523.7291648	total: 127ms	remaining: 1.5s
78:	learn: 25375.8892934	total: 128ms	remaining: 1.49s
79:	learn: 25244.1345056	total: 129ms	remaining: 1.48s
80:	learn: 25102.8179661	total: 130ms	remaining: 1.48s
81:	learn: 24945.6053063	total: 131ms	remaining: 1.47s
82:	learn: 24817.2933621	total: 132ms	remaining: 1.46s
83:	learn: 24706.0069247	total: 133ms	remaining: 1.45s
84:	learn: 24565.6726910	total: 134ms	remaining: 1.44s
85:	learn: 24435.3307798	total: 135ms	remaining: 1.44s
86:	learn: 24304.1274308	total: 136ms	remaining: 1.43s
87:	learn: 24193.5158294	total: 137ms	remaining: 1.42s
88:	learn: 24094.8097830	total: 138ms	remaining: 1.42s
89:	learn: 23997.6030146	total: 139ms	remaining: 1.41s
90:	learn: 23893.6302688	total: 140ms	remaining: 1.4s
91:	learn: 23775.4897984	total: 142ms	remaining: 1.4s
92:	learn: 23689.5489692	total: 144ms	remaining: 1.4s
93:	learn: 23606.0044329	total: 145ms	remaining: 1.4s
94:	learn: 23492.4953684	total: 146ms	remaining: 1.39s
95:	learn: 23395.5290901	total: 147ms	remaining: 1.39s
96:	learn: 23288.3759023	total: 148ms	remaining: 1.38s
97:	learn: 23211.8632700	total: 149ms	remaining: 1.37s
98:	learn: 23144.9144469	total: 150ms	remaining: 1.36s
99:	learn: 23052.2754975	total: 151ms	remaining: 1.36s
100:	learn: 22964.8457470	total: 152ms	remaining: 1.35s
101:	learn: 22886.2844499	total: 153ms	remaining: 1.34s
102:	learn: 22815.0198804	total: 154ms	remaining: 1.34s
103:	learn: 22714.3874730	total: 154ms	remaining: 1.33s
104:	learn: 22636.1034526	total: 155ms	remaining: 1.32s
105:	learn: 22541.2908133	total: 156ms	remaining: 1.32s
106:	learn: 22483.8092543	total: 157ms	remaining: 1.31s
107:	learn: 22429.6316934	total: 158ms	remaining: 1.3s
108:	learn: 22354.6102082	total: 159ms	remaining: 1.3s
109:	learn: 22283.3262554	total: 160ms	remaining: 1.3s
110:	learn: 22210.6429971	total: 161ms	remaining: 1.29s
111:	learn: 22133.0482646	total: 162ms	remaining: 1.28s
112:	learn: 22079.6172568	total: 163ms	remaining: 1.28s
113:	learn: 21993.7865734	total: 164ms	remaining: 1.27s
114:	learn: 21929.7700314	total: 165ms	remaining: 1.27s
115:	learn: 21872.2364823	total: 166ms	remaining: 1.26s
116:	learn: 21776.5213508	total: 166ms	remaining: 1.25s
117:	learn: 21698.5527370	total: 167ms	remaining: 1.25s
118:	learn: 21653.9120454	total: 168ms	remaining: 1.25s
119:	learn: 21580.3554433	total: 169ms	remaining: 1.24s
120:	learn: 21512.2940686	total: 170ms	remaining: 1.24s
121:	learn: 21444.8025871	total: 171ms	remaining: 1.23s
122:	learn: 21394.5674513	total: 172ms	remaining: 1.23s
123:	learn: 21331.9238759	total: 174ms	remaining: 1.23s
124:	learn: 21259.6609283	total: 175ms	remaining: 1.22s
125:	learn: 21189.1757028	total: 175ms	remaining: 1.22s
126:	learn: 21127.4127003	total: 177ms	remaining: 1.21s
127:	learn: 21094.6628752	total: 178ms	remaining: 1.21s
128:	learn: 21052.4763377	total: 179ms	remaining: 1.21s
129:	learn: 21009.2288108	total: 180ms	remaining: 1.21s
130:	learn: 20940.3528339	total: 182ms	remaining: 1.2s
131:	learn: 20876.2019000	total: 182ms	remaining: 1.2s
132:	learn: 20823.3028945	total: 183ms	remaining: 1.2s
133:	learn: 20775.6898583	total: 184ms	remaining: 1.19s
134:	learn: 20724.8613612	total: 186ms	remaining: 1.19s
135:	learn: 20698.4967919	total: 187ms	remaining: 1.19s
136:	learn: 20615.8465776	total: 188ms	remaining: 1.18s
137:	learn: 20576.2058928	total: 189ms	remaining: 1.18s
138:	learn: 20530.6619411	total: 191ms	remaining: 1.18s
139:	learn: 20497.0679942	total: 192ms	remaining: 1.18s
140:	learn: 20455.6026534	total: 193ms	remaining: 1.17s
141:	learn: 20409.3572215	total: 194ms	remaining: 1.17s
142:	learn: 20352.4545627	total: 195ms	remaining: 1.17s
143:	learn: 20306.8625089	total: 196ms	remaining: 1.17s
144:	learn: 20274.1444157	total: 197ms	remaining: 1.16s
145:	learn: 20231.9637896	total: 198ms	remaining: 1.16s
146:	learn: 20193.2920858	total: 199ms	remaining: 1.15s
147:	learn: 20141.5642737	total: 200ms	remaining: 1.15s
148:	learn: 20093.6339975	total: 201ms	remaining: 1.15s
149:	learn: 20050.7779410	total: 203ms	remaining: 1.15s
150:	learn: 20002.7724748	total: 205ms	remaining: 1.15s
151:	learn: 19960.5008360	total: 207ms	remaining: 1.15s
152:	learn: 19909.1059621	total: 208ms	remaining: 1.15s
153:	learn: 19883.9469385	total: 210ms	remaining: 1.15s
154:	learn: 19834.4750930	total: 212ms	remaining: 1.16s
155:	learn: 19789.6562961	total: 214ms	remaining: 1.16s
156:	learn: 19744.7583555	total: 216ms	remaining: 1.16s
157:	learn: 19716.6823172	total: 217ms	remaining: 1.16s
158:	learn: 19688.7374763	total: 219ms	remaining: 1.16s
159:	learn: 19665.8860312	total: 221ms	remaining: 1.16s
160:	learn: 19620.6932862	total: 223ms	remaining: 1.16s
161:	learn: 19586.8423315	total: 225ms	remaining: 1.16s
162:	learn: 19544.2008107	total: 227ms	remaining: 1.16s
163:	learn: 19515.0837357	total: 228ms	remaining: 1.16s
164:	learn: 19474.9896573	total: 229ms	remaining: 1.16s
165:	learn: 19443.5246604	total: 231ms	remaining: 1.16s
166:	learn: 19406.8265254	total: 232ms	remaining: 1.16s
167:	learn: 19380.7674393	total: 233ms	remaining: 1.15s
168:	learn: 19338.4266665	total: 235ms	remaining: 1.16s
169:	learn: 19317.7003221	total: 236ms	remaining: 1.15s
170:	learn: 19278.8732448	total: 238ms	remaining: 1.15s
171:	learn: 19243.5061000	total: 240ms	remaining: 1.16s
172:	learn: 19219.3082481	total: 241ms	remaining: 1.15s
173:	learn: 19186.0633449	total: 243ms	remaining: 1.15s
174:	learn: 19157.6998940	total: 245ms	remaining: 1.15s
175:	learn: 19112.5453582	total: 246ms	remaining: 1.15s
176:	learn: 19078.6407435	total: 248ms	remaining: 1.15s
177:	learn: 19054.6590665	total: 249ms	remaining: 1.15s
178:	learn: 19009.5981361	total: 250ms	remaining: 1.15s
179:	learn: 18974.2049604	total: 251ms	remaining: 1.14s
180:	learn: 18940.4566814	total: 252ms	remaining: 1.14s
181:	learn: 18917.3551384	total: 253ms	remaining: 1.14s
182:	learn: 18884.1234946	total: 254ms	remaining: 1.14s
183:	learn: 18849.8034855	total: 256ms	remaining: 1.13s
184:	learn: 18819.6230692	total: 257ms	remaining: 1.13s
185:	learn: 18792.2599596	total: 258ms	remaining: 1.13s
186:	learn: 18765.4714329	total: 259ms	remaining: 1.13s
187:	learn: 18731.2516705	total: 260ms	remaining: 1.12s
188:	learn: 18697.5353554	total: 261ms	remaining: 1.12s
189:	learn: 18648.5326474	total: 262ms	remaining: 1.12s
190:	learn: 18619.9615359	total: 263ms	remaining: 1.11s
191:	learn: 18582.5184178	total: 264ms	remaining: 1.11s
192:	learn: 18542.8580477	total: 266ms	remaining: 1.11s
193:	learn: 18510.1986153	total: 267ms	remaining: 1.11s
194:	learn: 18486.8325633	total: 268ms	remaining: 1.1s
195:	learn: 18458.7819380	total: 269ms	remaining: 1.1s
196:	learn: 18420.6133809	total: 270ms	remaining: 1.1s
197:	learn: 18396.8227883	total: 271ms	remaining: 1.1s
198:	learn: 18357.1017150	total: 272ms	remaining: 1.09s
199:	learn: 18336.1658851	total: 273ms	remaining: 1.09s
200:	learn: 18312.3553881	total: 274ms	remaining: 1.09s
201:	learn: 18280.5963916	total: 275ms	remaining: 1.09s
202:	learn: 18249.7503982	total: 276ms	remaining: 1.08s
203:	learn: 18217.1905244	total: 277ms	remaining: 1.08s
204:	learn: 18196.6209802	total: 279ms	remaining: 1.08s
205:	learn: 18142.9444078	total: 280ms	remaining: 1.08s
206:	learn: 18123.6806992	total: 281ms	remaining: 1.07s
207:	learn: 18103.7297993	total: 281ms	remaining: 1.07s
208:	learn: 18084.5220470	total: 282ms	remaining: 1.07s
209:	learn: 18054.4603929	total: 283ms	remaining: 1.07s
210:	learn: 18045.4163979	total: 284ms	remaining: 1.06s
211:	learn: 18012.9103496	total: 285ms	remaining: 1.06s
212:	learn: 17980.7259405	total: 286ms	remaining: 1.06s
213:	learn: 17949.5456392	total: 287ms	remaining: 1.05s
214:	learn: 17923.1433762	total: 288ms	remaining: 1.05s
215:	learn: 17881.3475292	total: 289ms	remaining: 1.05s
216:	learn: 17851.3522703	total: 290ms	remaining: 1.04s
217:	learn: 17835.8001479	total: 291ms	remaining: 1.04s
218:	learn: 17800.2075057	total: 292ms	remaining: 1.04s
219:	learn: 17794.0535737	total: 293ms	remaining: 1.04s
220:	learn: 17760.6532471	total: 293ms	remaining: 1.03s
221:	learn: 17748.0988153	total: 294ms	remaining: 1.03s
222:	learn: 17713.1362932	total: 295ms	remaining: 1.03s
223:	learn: 17690.6358826	total: 296ms	remaining: 1.02s
224:	learn: 17656.2096775	total: 297ms	remaining: 1.02s
225:	learn: 17620.8051649	total: 298ms	remaining: 1.02s
226:	learn: 17588.9259141	total: 299ms	remaining: 1.02s
227:	learn: 17583.6641752	total: 300ms	remaining: 1.01s
228:	learn: 17551.9241755	total: 301ms	remaining: 1.01s
229:	learn: 17535.4160140	total: 302ms	remaining: 1.01s
230:	learn: 17496.7993369	total: 303ms	remaining: 1.01s
231:	learn: 17491.9132914	total: 304ms	remaining: 1s
232:	learn: 17473.9335306	total: 305ms	remaining: 1s
233:	learn: 17459.3815599	total: 306ms	remaining: 1s
234:	learn: 17435.0419935	total: 307ms	remaining: 998ms
235:	learn: 17421.9288806	total: 307ms	remaining: 995ms
236:	learn: 17404.9509652	total: 308ms	remaining: 993ms
237:	learn: 17396.3397565	total: 309ms	remaining: 990ms
238:	learn: 17363.5707345	total: 310ms	remaining: 987ms
239:	learn: 17348.6243028	total: 311ms	remaining: 985ms
240:	learn: 17344.3827541	total: 312ms	remaining: 984ms
241:	learn: 17316.2930267	total: 314ms	remaining: 982ms
242:	learn: 17293.8424112	total: 314ms	remaining: 979ms
243:	learn: 17251.7383524	total: 316ms	remaining: 978ms
244:	learn: 17222.0256935	total: 318ms	remaining: 979ms
245:	learn: 17215.4120018	total: 319ms	remaining: 977ms
246:	learn: 17185.8797908	total: 321ms	remaining: 980ms
247:	learn: 17162.6735413	total: 324ms	remaining: 982ms
248:	learn: 17128.8826378	total: 325ms	remaining: 980ms
249:	learn: 17112.1944427	total: 326ms	remaining: 978ms
250:	learn: 17080.3775869	total: 329ms	remaining: 982ms
251:	learn: 17066.7007866	total: 330ms	remaining: 979ms
252:	learn: 17062.8104191	total: 331ms	remaining: 977ms
253:	learn: 17059.1693153	total: 332ms	remaining: 975ms
254:	learn: 17030.2682194	total: 333ms	remaining: 972ms
255:	learn: 17026.8531314	total: 335ms	remaining: 972ms
256:	learn: 17008.5413507	total: 336ms	remaining: 972ms
257:	learn: 16990.4633218	total: 337ms	remaining: 970ms
258:	learn: 16951.0968793	total: 338ms	remaining: 968ms
259:	learn: 16924.8220407	total: 340ms	remaining: 967ms
260:	learn: 16918.7761417	total: 341ms	remaining: 965ms
261:	learn: 16910.7820830	total: 342ms	remaining: 963ms
262:	learn: 16868.7125771	total: 343ms	remaining: 962ms
263:	learn: 16821.4145586	total: 344ms	remaining: 960ms
264:	learn: 16809.8508010	total: 345ms	remaining: 958ms
265:	learn: 16781.1804567	total: 348ms	remaining: 959ms
266:	learn: 16765.6818550	total: 349ms	remaining: 957ms
267:	learn: 16740.0198529	total: 350ms	remaining: 955ms
268:	learn: 16709.0234277	total: 351ms	remaining: 953ms
269:	learn: 16689.4249582	total: 353ms	remaining: 954ms
270:	learn: 16682.3363023	total: 354ms	remaining: 951ms
271:	learn: 16667.1999097	total: 357ms	remaining: 955ms
272:	learn: 16638.9854335	total: 360ms	remaining: 958ms
273:	learn: 16628.4015203	total: 361ms	remaining: 956ms
274:	learn: 16605.8050547	total: 362ms	remaining: 954ms
275:	learn: 16592.2134646	total: 363ms	remaining: 952ms
276:	learn: 16566.9515324	total: 364ms	remaining: 950ms
277:	learn: 16549.8812580	total: 365ms	remaining: 948ms
278:	learn: 16527.9348661	total: 366ms	remaining: 946ms
279:	learn: 16502.7712420	total: 367ms	remaining: 944ms
280:	learn: 16483.6964584	total: 368ms	remaining: 942ms
281:	learn: 16462.4918400	total: 369ms	remaining: 940ms
282:	learn: 16448.5272441	total: 372ms	remaining: 942ms
283:	learn: 16425.0710682	total: 373ms	remaining: 940ms
284:	learn: 16398.5748814	total: 374ms	remaining: 938ms
285:	learn: 16382.2823838	total: 375ms	remaining: 936ms
286:	learn: 16373.5934912	total: 376ms	remaining: 934ms
287:	learn: 16354.5648584	total: 377ms	remaining: 932ms
288:	learn: 16323.1421087	total: 378ms	remaining: 930ms
289:	learn: 16293.7112166	total: 379ms	remaining: 927ms
290:	learn: 16262.1771292	total: 380ms	remaining: 925ms
291:	learn: 16231.9996689	total: 380ms	remaining: 923ms
292:	learn: 16217.7720887	total: 381ms	remaining: 920ms
293:	learn: 16183.7616761	total: 382ms	remaining: 918ms
294:	learn: 16181.4771978	total: 383ms	remaining: 916ms
295:	learn: 16161.3912851	total: 384ms	remaining: 914ms
296:	learn: 16147.1221607	total: 385ms	remaining: 912ms
297:	learn: 16119.3046356	total: 386ms	remaining: 910ms
298:	learn: 16093.0529990	total: 387ms	remaining: 907ms
299:	learn: 16078.6890984	total: 388ms	remaining: 905ms
300:	learn: 16056.5978981	total: 389ms	remaining: 903ms
301:	learn: 16035.6274474	total: 390ms	remaining: 901ms
302:	learn: 16002.9439024	total: 391ms	remaining: 899ms
303:	learn: 15983.3755540	total: 392ms	remaining: 897ms
304:	learn: 15969.5171809	total: 393ms	remaining: 895ms
305:	learn: 15946.1899536	total: 394ms	remaining: 893ms
306:	learn: 15937.3568514	total: 394ms	remaining: 890ms
307:	learn: 15918.2832220	total: 395ms	remaining: 889ms
308:	learn: 15900.8862302	total: 396ms	remaining: 886ms
309:	learn: 15888.0381301	total: 397ms	remaining: 885ms
310:	learn: 15845.1418549	total: 399ms	remaining: 883ms
311:	learn: 15827.6867818	total: 402ms	remaining: 886ms
312:	learn: 15788.3374223	total: 403ms	remaining: 884ms
313:	learn: 15771.2707008	total: 404ms	remaining: 882ms
314:	learn: 15751.3497948	total: 405ms	remaining: 880ms
315:	learn: 15731.5331565	total: 405ms	remaining: 877ms
316:	learn: 15715.3622404	total: 406ms	remaining: 875ms
317:	learn: 15698.8349086	total: 407ms	remaining: 873ms
318:	learn: 15667.4632752	total: 408ms	remaining: 871ms
319:	learn: 15644.8783842	total: 409ms	remaining: 869ms
320:	learn: 15621.5968254	total: 410ms	remaining: 866ms
321:	learn: 15585.3485489	total: 410ms	remaining: 864ms
322:	learn: 15570.1915217	total: 411ms	remaining: 862ms
323:	learn: 15543.4271692	total: 412ms	remaining: 860ms
324:	learn: 15510.9294357	total: 413ms	remaining: 858ms
325:	learn: 15486.0478625	total: 414ms	remaining: 856ms
326:	learn: 15460.8995712	total: 415ms	remaining: 854ms
327:	learn: 15433.0254953	total: 416ms	remaining: 852ms
328:	learn: 15401.0456160	total: 417ms	remaining: 850ms
329:	learn: 15374.6636155	total: 417ms	remaining: 848ms
330:	learn: 15351.6561986	total: 418ms	remaining: 846ms
331:	learn: 15328.4538907	total: 419ms	remaining: 844ms
332:	learn: 15307.8447950	total: 420ms	remaining: 842ms
333:	learn: 15285.0085420	total: 421ms	remaining: 840ms
334:	learn: 15274.5415167	total: 422ms	remaining: 838ms
335:	learn: 15258.1672910	total: 423ms	remaining: 836ms
336:	learn: 15250.4993718	total: 424ms	remaining: 834ms
337:	learn: 15231.2314448	total: 425ms	remaining: 832ms
338:	learn: 15214.3175095	total: 426ms	remaining: 830ms
339:	learn: 15188.0482624	total: 426ms	remaining: 828ms
340:	learn: 15170.2499861	total: 427ms	remaining: 826ms
341:	learn: 15148.3645068	total: 428ms	remaining: 824ms
342:	learn: 15133.2083910	total: 429ms	remaining: 822ms
343:	learn: 15104.5171397	total: 430ms	remaining: 820ms
344:	learn: 15063.6025280	total: 431ms	remaining: 819ms
345:	learn: 15042.8515714	total: 432ms	remaining: 817ms
346:	learn: 15037.5218394	total: 433ms	remaining: 815ms
347:	learn: 15035.8669879	total: 434ms	remaining: 813ms
348:	learn: 15021.1210232	total: 435ms	remaining: 811ms
349:	learn: 15007.0908080	total: 435ms	remaining: 809ms
350:	learn: 14994.3925910	total: 436ms	remaining: 807ms
351:	learn: 14969.2741874	total: 437ms	remaining: 805ms
352:	learn: 14957.5004981	total: 438ms	remaining: 803ms
353:	learn: 14935.1153346	total: 439ms	remaining: 801ms
354:	learn: 14909.5700130	total: 440ms	remaining: 799ms
355:	learn: 14890.3374642	total: 441ms	remaining: 797ms
356:	learn: 14882.1914402	total: 442ms	remaining: 796ms
357:	learn: 14867.6804676	total: 443ms	remaining: 794ms

In [52]:
r2_score(y_test,predicted)

0.9062316063016054

In [53]:
comparison_df = pd.concat([
        y_test.reset_index(drop=True),
        pd.DataFrame(predicted, columns=["Predicted"])],axis=1)

In [54]:
comparison_df

     SalePrice      Predicted
0       154500  140684.968405
1       325000  368215.038660
2       115000  119824.948561
3       159000  136194.878008
4       315500  330062.352970
..         ...            ...
433     139000  134430.273767
434     126175  123350.015396
435     205950  206046.884585
436     110000  131237.118561
437     485000  532927.746654

[438 rows x 2 columns]

In [57]:
joblib.dump(CBR, "model.pkl")

['model.pkl']