In [1]:
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect('customer_intelligence.db')

In [3]:
df = pd.read_csv(r"../data/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [4]:
df.to_sql('customers',conn,if_exists='replace',index=False)

7043

In [ ]:
#total customer

In [7]:
query = """SELECT COUNT(*) AS total_customers FROM customers;"""
result = pd.read_sql(query, conn)
result

   total_customers
0             7043

In [ ]:
#total churened customer

In [8]:
query = """SELECT COUNT(Churn) AS total_customers FROM customers where Churn = "Yes";"""
result = pd.read_sql(query, conn)
result

   total_customers
0             1869

In [ ]:
#churn rate

In [10]:
query = """SELECT (SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0/ COUNT(*)) AS churn_rate FROM customers;"""
result = pd.read_sql(query, conn)
result

   churn_rate
0   26.536987

In [ ]:
#chrun by contract

In [11]:
query = """SELECT Contract,COUNT(*) AS churned_customers
FROM customers
WHERE Churn = 'Yes'
GROUP BY Contract
ORDER BY churned_customers DESC;"""
result = pd.read_sql(query, conn)
result

         Contract  churned_customers
0  Month-to-month               1655
1        One year                166
2        Two year                 48

In [ ]:
#payment method

In [17]:
query =""" SELECT  PaymentMethod,COUNT(*) AS CHURENED_CUSTOMER
FROM customers
WHERE Churn = "Yes"
GROUP BY PaymentMethod
ORDER BY CHURENED_CUSTOMER DESC;"""
result= pd.read_sql(query, conn)
result

               PaymentMethod  CHURENED_CUSTOMER
0           Electronic check               1071
1               Mailed check                308
2  Bank transfer (automatic)                258
3    Credit card (automatic)                232

In [ ]:
#churn by internet service

In [18]:
query =""" SELECT  InternetService,COUNT(*) AS CHURENED_CUSTOMER
FROM customers
WHERE Churn = "Yes"
GROUP BY InternetService
ORDER BY CHURENED_CUSTOMER DESC;"""
result= pd.read_sql(query, conn)
result

  InternetService  CHURENED_CUSTOMER
0     Fiber optic               1297
1             DSL                459
2              No                113

In [ ]:
#average mothly charges

In [20]:
query = """ SELECT AVG(MonthlyCharges) AS AVERAGE_CHARGES
FROM customers;"""
result = pd.read_sql(query,conn)
result

   AVERAGE_CHARGES
0        64.761692

In [ ]:
#total charges

In [21]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [22]:
query = """ SELECT AVG(TotalCharges) AS AVERAGE_CHARGES
FROM customers;"""
result = pd.read_sql(query,conn)
result

   AVERAGE_CHARGES
0      2279.734304

In [ ]:
#high values customers

In [23]:
query = """SELECT customerID,Contract,tenure,MonthlyCharges,TotalCharges
FROM customers
ORDER BY TotalCharges DESC
LIMIT 10;"""
result = pd.read_sql(query, conn)
result

   customerID        Contract  tenure  MonthlyCharges TotalCharges
0  9093-FPDLG  Month-to-month      11           94.20        999.9
1  4536-PLEQY  Month-to-month      12           85.05        999.8
2  5899-MQZZL  Month-to-month      13           75.00       999.45
3  6051-PTVNS        One year      55           19.15        998.1
4  8249-THVEC        One year      51           19.40       997.75
5  6328-ZPBGN  Month-to-month      11           95.15       997.65
6  7297-DVYGA        One year      51           19.85       996.95
7  6243-OZGFH  Month-to-month      23           44.95       996.85
8  0484-JPBRU  Month-to-month      41           25.25       996.45
9  2971-SGAFL  Month-to-month      13           78.75       995.35

In [ ]:
#high risk customers

In [27]:
query = """SELECT customerID,Contract,tenure,MonthlyCharges,TotalCharges,Churn
FROM customers
WHERE Contract = 'Month-to-month'
  AND MonthlyCharges >= 70
  AND Churn = "No"
ORDER BY MonthlyCharges DESC
LIMIT 10;"""
result = pd.read_sql(query, conn)
result

   customerID        Contract  tenure  MonthlyCharges TotalCharges Churn
0  8016-NCFVO  Month-to-month      55          116.50      6382.55    No
1  9659-QEQSY  Month-to-month      45          115.65       5125.5    No
2  6710-HSJRD  Month-to-month      61          114.10      7132.15    No
3  0771-WLCLA  Month-to-month      16          112.95      1882.55    No
4  9481-IEBZY  Month-to-month      72          112.90       8061.5    No
5  2587-EKXTS  Month-to-month      44          111.50      4915.15    No
6  7130-YXBRO  Month-to-month      48          111.45       5315.1    No
7  3292-PBZEJ  Month-to-month      11          111.40      1183.05    No
8  6168-YBYNP  Month-to-month      59          111.35      6519.75    No
9  2067-QYTCF  Month-to-month      64          111.15       6953.4    No

In [ ]:
#customer with long tenure

In [28]:
query = """SELECT customerID,Contract,tenure,MonthlyCharges,TotalCharges,Churn
FROM customers
ORDER BY tenure DESC
LIMIT 10;"""
result = pd.read_sql(query, conn)
result

   customerID  Contract  tenure  MonthlyCharges TotalCharges Churn
0  5248-YGIJN  Two year      72           90.25      6369.45    No
1  6234-RAAPL  Two year      72           99.90       7251.7    No
2  5954-BDFSG  Two year      72          107.50       7853.7    No
3  0526-SXDJP  Two year      72           42.10         2962    No
4  9848-JQJTX  Two year      72          100.90      7459.05    No
5  6728-DKUCO  One year      72          104.15      7303.05    No
6  2848-YXSMW  Two year      72           19.40      1363.25    No
7  6734-PSBAW  Two year      72           23.55      1723.95    No
8  3146-MSEGF  Two year      72           88.05      6425.65    No
9  5997-OPVFA  Two year      72           89.05      6254.45    No

In [ ]:
#customer with high monlthy cahrges

In [29]:
query = """ SELECT customerID,Contract,tenure,MonthlyCharges,TotalCharges,Churn
FROM customers
ORDER BY MonthlyCharges DESC
LIMIT 10;"""
result = pd.read_sql(query, conn)
result

   customerID        Contract  tenure  MonthlyCharges TotalCharges Churn
0  7569-NMZYQ        Two year      72          118.75      8672.45    No
1  8984-HPEMB        Two year      71          118.65       8477.6    No
2  5989-AXPUC        Two year      68          118.60      7990.05    No
3  5734-EJKXG        One year      61          118.60       7365.7    No
4  8199-ZLLSA        One year      67          118.35      7804.15   Yes
5  9924-JPRMC        Two year      72          118.20      8547.15    No
6  2889-FPWRM        One year      72          117.80       8684.8   Yes
7  3810-DVDQQ        Two year      72          117.60       8308.9    No
8  9739-JLPQJ        Two year      72          117.50       8670.1    No
9  2302-ANTDP  Month-to-month      48          117.45       5438.9   Yes

In [ ]:
#customer segment based on service

In [ ]:
query = """SELECT InternetService,COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS churn_rate
FROM customers
GROUP BY InternetService
ORDER BY total_customers DESC;"""
result = pd.read_sql(query, conn)
result

  InternetService  total_customers  churned_customers  churn_rate
0     Fiber optic             3096               1297       41.89
1             DSL             2421                459       18.96
2              No             1526                113        7.40

In [ ]:
#revenue analysis

In [32]:
query =""" SELECT ROUND(SUM(MonthlyCharges),2) AS TOTAL_MONTHLY_CHARGES,
ROUND(AVG(MonthlyCharges),2) AS AVERAGE_MONTHLY_CHARGES
FROM customers;"""
result = pd.read_sql(query, conn)
result

   TOTAL_MONTHLY_CHARGES  AVERAGE_MONTHLY_CHARGES
0               456116.6                    64.76